pub mod async_api;
pub mod async_framework;
pub mod blocking_api;
pub mod examples;
// Generated by wit-bindgen in its own style; skip rustfmt so regenerating it does
// not reformat the whole file.
#[allow(warnings)]
#[rustfmt::skip]
pub mod wasm_bindings;
pub mod wasm_bindings_ext;

use wasm_bindings::exports::robot::{Color, Configuration, Guest};

struct Component;

impl Guest for Component {
    fn setup() -> Configuration {
        Configuration {
            name: "Liner".to_string(),
            color_main: Color { r: 255, g: 0, b: 0 },
            color_secondary: Color { r: 0, g: 255, b: 0 },
            width_axle: 100.0,
            length_front: 100.0,
            length_back: 20.0,
            clearing_back: 3.0,
            wheel_diameter: 25.0,
            gear_ratio_num: 1,
            gear_ratio_den: 20,
            front_sensors_spacing: 4.0,
            front_sensors_height: 4.0,
        }
    }

    fn run() -> () {
        examples::toy::run();
        // examples::basic_pid::run(4.0);
        // examples::pid_with_memory::run(4.0);
        // async_framework::run(examples::nb::toy::run());
        // async_framework::run(examples::telemetry_test::run(4.0));
        // async_framework::run(examples::nb::parallel_tasks::run(4.0));
        // async_framework::run(examples::nb::tasks_with_channels::run(4.0));
    }
}

wasm_bindings::export!(Component with_types_in wasm_bindings);
